force-app/main/default/objects/Student__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentAssisment__c/fields/No_Of_Student__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Student__c</fullName>
    <label>No. Of Student</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StudentAssisment__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <externalId>true</externalId>
    <label>Subject Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentTriggerHandler.cls
public class StudentTriggerHandler {
    public static void updateStudentAssisment(List<Student__c> studentList){
        
         List<id> SubjectId = new List<id>();
        for(Student__c sub:studentList){
            SubjectId.add(sub.Subject__c);
        }
        List<Subject__c> totalSub = [SELECT Name FROM Subject__c WHERE Id IN :SubjectId];
        List<Student__c> totaluser = [SELECT Name, Subject__c FROM Student__c WHERE Subject__c IN :SubjectId];
        
        map<Subject__c,integer> numberOfStudentPerSubject = new map<Subject__c,integer>();
        
        for(Subject__c  sub: totalSub){
            for(Student__c stu:totaluser){
            if(!numberOfStudentPerSubject.ContainsKey(sub)){
                numberOfStudentPerSubject.put(sub,1);
                    }else{
                        if(sub.id == stu.Subject__c){
                             numberOfStudentPerSubject.put(sub,numberOfStudentPerSubject.get(sub) +1);
                        }
                    }
        }
        }
        
        List<StudentAssisment__c> stuAssign = new List<StudentAssisment__c>();
        
        for(Subject__c sub:numberOfStudentPerSubject.keyset()){
            StudentAssisment__c stuAss = new StudentAssisment__c();
            stuAss.Subject_Name__c = sub.Name;
            stuAss.No_Of_Student__c = numberOfStudentPerSubject.get(sub);
            
            stuAssign.add(stuAss);
        }
        
        upsert stuAssign;
    }
}